name = "Elly Server Pack"
author = "spoemeo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d482aa8df9c915462d050b4ff9ddee5cffcead6f04fd56321ddf7df9031dc89"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
