name = "Elly Server Pack"
author = "spoemeo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f51aa250c6fe9801efc30ef7a9a8c7eba653f2e29996dcca8befbcdf75c1b78"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
