name = "Elly Server Pack"
author = "spoemeo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a11d5966c80856fbae159139db378408734dc8127492986a44cd5c3739b34bb"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
